// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ass_thieubvph20221.Models;

#nullable disable

namespace ass_thieubvph20221.Migrations
{
    [DbContext(typeof(giayDBcontext))]
    partial class giayDBcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ass_thieubvph20221.Models.ChiTietGioHang", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("idGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("idGioHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("soLuong")
                        .HasColumnType("int");

                    b.Property<int?>("trangThai")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idGiay");

                    b.HasIndex("idGioHang");

                    b.ToTable("ChiTietGioHangs");
                });

            modelBuilder.Entity("ass_thieubvph20221.Models.chiTietHoaDon", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("donGia")
                        .HasColumnType("int");

                    b.Property<int?>("giamGia")
                        .HasColumnType("int");

                    b.Property<Guid?>("idGiay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("idHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("soLuong")
                        .HasColumnType("int");

                    b.Property<int?>("thanhTien")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idGiay");

                    b.HasIndex("idHoaDon");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("ass_thieubvph20221.Models.giay", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chatLieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("donGiaNhap")
                        .HasColumnType("int");

                    b.Property<int?>("donGiaban")
                        .HasColumnType("int");

                    b.Property<string>("ghiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("soLuong")
                        .HasColumnType("int");

                    b.Property<string>("tenGiay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Giays");
                });

            modelBuilder.Entity("ass_thieubvph20221.Models.GioHang", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("mota")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("idKhachHang");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("ass_thieubvph20221.Models.hoaDon", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ngayBan")
                        .HasColumnType("datetime2");

                    b.Property<int?>("tongTien")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idKhachHang");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("ass_thieubvph20221.Models.khachHang", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenKH")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("ass_thieubvph20221.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("ass_thieubvph20221.Models.giay", "Giay")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("idGiay");

                    b.HasOne("ass_thieubvph20221.Models.GioHang", "GioHang")
                        .WithMany("CChiTietGioHangs")
                        .HasForeignKey("idGioHang");

                    b.Navigation("Giay");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("ass_thieubvph20221.Models.chiTietHoaDon", b =>
                {
                    b.HasOne("ass_thieubvph20221.Models.giay", "Giay")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("idGiay");

                    b.HasOne("ass_thieubvph20221.Models.hoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("idHoaDon");

                    b.Navigation("Giay");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("ass_thieubvph20221.Models.GioHang", b =>
                {
                    b.HasOne("ass_thieubvph20221.Models.khachHang", "KhachHang")
                        .WithMany("GioHangs")
                        .HasForeignKey("idKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("ass_thieubvph20221.Models.hoaDon", b =>
                {
                    b.HasOne("ass_thieubvph20221.Models.khachHang", "KhachHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("idKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("ass_thieubvph20221.Models.giay", b =>
                {
                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("ass_thieubvph20221.Models.GioHang", b =>
                {
                    b.Navigation("CChiTietGioHangs");
                });

            modelBuilder.Entity("ass_thieubvph20221.Models.hoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("ass_thieubvph20221.Models.khachHang", b =>
                {
                    b.Navigation("GioHangs");

                    b.Navigation("HoaDon");
                });
#pragma warning restore 612, 618
        }
    }
}
